In [2]:
!pip install lazypredict

In [3]:
#import essentials libraries
import pandas as pd
import numpy as np
import lazypredict

In [4]:
data=pd.read_csv("IRIS.csv")
data.head()


sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
x=data.drop(['species'],axis=1)
y=data['species']

In [ ]:
from lazypredict.Supervised import LazyClassifier
from sklearn.model_selection import train_test_split

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
clf=LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models,pred=clf.fit(xtrain,xtest,ytrain,ytest)

100%|██████████████████████████████████████████████████████████████████████████████████| 29/29 [00:02<00:00, 13.15it/s]


In [ ]:
print(models)

                               Accuracy  Balanced Accuracy ROC AUC  F1 Score  \
Model                                                                          
LGBMClassifier                     1.00               1.00    None      1.00   
BaggingClassifier                  1.00               1.00    None      1.00   
SVC                                1.00               1.00    None      1.00   
SGDClassifier                      1.00               1.00    None      1.00   
DecisionTreeClassifier             1.00               1.00    None      1.00   
RandomForestClassifier             1.00               1.00    None      1.00   
QuadraticDiscriminantAnalysis      1.00               1.00    None      1.00   
ExtraTreesClassifier               1.00               1.00    None      1.00   
KNeighborsClassifier               1.00               1.00    None      1.00   
NuSVC                              1.00               1.00    None      1.00   
LogisticRegression                 1.00 

In [ ]:
from sklearn.ensemble import RandomForestClassifier

classifier=RandomForestClassifier()
classifier.fit(xtrain,ytrain)
ypred=classifier.predict(xtest)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

print(confusion_matrix(ytest,ypred))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [ ]:
print(classification_report(ytest,ypred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [ ]:
print(accuracy_score(ytest,ypred))

1.0


In [ ]:
data.tail()

sepal_length  sepal_width  petal_length  petal_width         species
145          6.70         3.00          5.20         2.30  Iris-virginica
146          6.30         2.50          5.00         1.90  Iris-virginica
147          6.50         3.00          5.20         2.00  Iris-virginica
148          6.20         3.40          5.40         2.30  Iris-virginica
149          5.90         3.00          5.10         1.80  Iris-virginica

In [ ]:
print(classifier.predict((np.array([[4,3,3,4]]))))

['Iris-virginica']


C:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
